import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ResumeProvider} from "@/providers/resume-provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Dev Resume',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} p-5 print:p-0`}>
        <ResumeProvider>
            {children}
        </ResumeProvider>
        </body>
        </html>
    )
}
